name: Create Docker image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and tag tccappmathvision image
        run: |
          docker build -t tccappmathvision:${{ github.sha }} .
      - name: Get image id
        id: vars
        run: echo ::set-output name=tag::$(docker images | awk '{print $3}' | awk 'NR==2')
      - name: Login to GitHub Packages
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Tag image id
        run: |
          docker tag ${{steps.vars.outputs.tag}} docker.pkg.github.com/andersonn-roberto/tcc-app-math-vision/tccappmathvision:${{ github.sha }}
      - name: Push to GitHub Packages
        run: |
          docker push docker.pkg.github.com/andersonn-roberto/tcc-app-math-vision/tccappmathvision:${{ github.sha }}
